spring:
  application:
    name: provider2
  datasource:
    url: jdbc:mysql://139.155.135.177:3316/springcloud2?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 8
      min-idle: 2
      validation-query: 'select 1'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # psCache, 缓存preparedStatement, 对支持游标的数据库性能有巨大的提升，oracle开启，mysql建议关闭
      pool-prepared-statements: false
      # psCache开启的时候有效
      max-open-prepared-statements: 100
      # 一个连接在被驱逐出连接池的时候，在连接池中最小的空闲时间，单位为毫秒
      min-evictable-idle-time-millis: 30000
      # 距离上次释放空闲连接的时间间隔
      time-between-eviction-runs-millis: 30000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7962/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 6001


mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ys.provider2.entity
